export const products = [
  // FASHION - ANKARA & AFRICAN WEAR (10 products)
  {
    id: 1,
    name: "Ankara Maxi Dress",
    brand: "Adwoa's Collection",
    price: 350,
    originalPrice: 450,
    rating: 4.8,
    reviews: 124,
    category: "Fashion",
    image: "https://res.cloudinary.com/dwsl2ktt2/image/upload/v1778669947/yyyr_rrilrc.avif",
    badge: "Sale",
    stock: 15,
    description: "Beautiful Ankara maxi dress with modern cut. Perfect for weddings and special occasions.",
  },
  {
    id: 2,
    name: "Kente Wrap Skirt",
    brand: "Heritage Ghana",
    price: 280,
    rating: 4.9,
    reviews: 89,
    category: "Fashion",
    image: "https://res.cloudinary.com/dwsl2ktt2/image/upload/v1778669947/xxx_peeq9k.jpg",
    badge: "New",
    stock: 8,
    description: "Authentic Kente wrap skirt handwoven by Ghanaian artisans. A timeless piece.",
  },
  {
    id: 3,
    name: "Ankara Peplum Blouse",
    brand: "Adwoa's Collection",
    price: 180,
    rating: 4.7,
    reviews: 156,
    category: "Fashion",
    image: "https://res.cloudinary.com/dwsl2ktt2/image/upload/v1778669947/jjb_pwzexw.jpg",
    stock: 20,
    description: "Stylish peplum blouse in vibrant Ankara print. Pairs perfectly with skirts or trousers.",
  },
  {
    id: 4,
    name: "African Print Jumpsuit",
    brand: "Modern Afrika",
    price: 420,
    originalPrice: 520,
    rating: 4.6,
    reviews: 78,
    category: "Fashion",
    image: "https://res.cloudinary.com/dwsl2ktt2/image/upload/v1778669948/yyyy_woib3l.jpg",
    badge: "Sale",
    stock: 5,
    description: "Contemporary jumpsuit with traditional African print. Modern elegance meets heritage.",
  },
  {
    id: 5,
    name: "Kente Evening Gown",
    brand: "Heritage Ghana",
    price: 850,
    rating: 5.0,
    reviews: 45,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1518611012118-628c1ce57a14?w=500&h=500&fit=crop",
    badge: "Premium",
    description: "Luxurious Kente evening gown for the most special occasions. Handwoven excellence.",
  },
  {
    id: 6,
    name: "Ankara Shift Dress",
    brand: "Adwoa's Collection",
    price: 290,
    rating: 4.5,
    reviews: 203,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1594938328870-9623159c8c99?w=500&h=500&fit=crop",
    description: "Comfortable shift dress in beautiful Ankara fabric. Perfect for work or casual outings.",
  },
  {
    id: 7,
    name: "Dashiki Maxi Kaftan",
    brand: "Modern Afrika",
    price: 320,
    rating: 4.8,
    reviews: 167,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1558171813-4c08833ed8a8?w=500&h=500&fit=crop",
    description: "Elegant dashiki kaftan in rich colors. Comfortable and stylish for any occasion.",
  },
  {
    id: 8,
    name: "Ankara Palazzo Pants",
    brand: "Adwoa's Collection",
    price: 220,
    rating: 4.6,
    reviews: 134,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1509631179150-0c3090bd39a4?w=500&h=500&fit=crop",
    description: "Flowy palazzo pants in stunning Ankara print. Comfort meets style.",
  },
  {
    id: 9,
    name: "Boubou African Dress",
    brand: "Heritage Ghana",
    price: 380,
    rating: 4.7,
    reviews: 92,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1539003020276-dab6ed6dc12f?w=500&h=500&fit=crop",
    description: "Traditional Boubou dress with modern touches. Perfect for cultural events.",
  },
  {
    id: 10,
    name: "Ankara Kimono Jacket",
    brand: "Modern Afrika",
    price: 195,
    originalPrice: 250,
    rating: 4.9,
    reviews: 211,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&h=500&fit=crop",
    badge: "Sale",
    description: "Versatile kimono jacket that transforms any outfit. A statement piece.",
  },

  // COSMETICS & MAKEUP (10 products)
  {
    id: 11,
    name: "Shea Butter Lip Gloss Set",
    brand: "Ghana Glow",
    price: 85,
    rating: 4.8,
    reviews: 342,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500&h=500&fit=crop",
    badge: "Bestseller",
    description: "Nourishing lip gloss set infused with Ghanaian shea butter. 6 gorgeous shades.",
  },
  {
    id: 12,
    name: "Natural Foundation - Cocoa",
    brand: "Ghana Glow",
    price: 120,
    rating: 4.7,
    reviews: 289,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1586495777744-44110f40c679?w=500&h=500&fit=crop",
    description: "Full coverage foundation made for African skin tones. 12 shades available.",
  },
  {
    id: 13,
    name: "African Black Soap Mascara",
    brand: "Natural Beauty GH",
    price: 65,
    rating: 4.6,
    reviews: 178,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38baa96?w=500&h=500&fit=crop",
    description: "Lengthening mascara with African black soap extracts. Gentle and effective.",
  },
  {
    id: 14,
    name: "Kente Inspired Eyeshadow Palette",
    brand: "Ghana Glow",
    price: 150,
    rating: 4.9,
    reviews: 456,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1599206676335-b0a1f3c27d5e?w=500&h=500&fit=crop",
    badge: "New",
    description: "Vibrant eyeshadow palette inspired by Kente colors. 18 stunning shades.",
  },
  {
    id: 15,
    name: "Shea Butter Highlighter",
    brand: "Natural Beauty GH",
    price: 95,
    rating: 4.8,
    reviews: 234,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1599733589046-10dc956d6c35?w=500&h=500&fit=crop",
    description: "Glowing highlighter with shea butter for smooth application. Golden shimmer.",
  },
  {
    id: 16,
    name: "Cocoa Butter Contour Kit",
    brand: "Ghana Glow",
    price: 135,
    rating: 4.7,
    reviews: 167,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1597225244660-1cd128c191a6?w=500&h=500&fit=crop",
    description: "Complete contour and bronzing kit. Perfect for sculpting African features.",
  },
  {
    id: 17,
    name: "Natural Brow Gel Duo",
    brand: "Natural Beauty GH",
    price: 55,
    rating: 4.5,
    reviews: 198,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1583241800698-e8ab01c058d7?w=500&h=500&fit=crop",
    description: "Dual-ended brow gel for perfectly defined brows. Long-lasting formula.",
  },
  {
    id: 18,
    name: "Coconut Oil Setting Spray",
    brand: "Ghana Glow",
    price: 75,
    rating: 4.6,
    reviews: 312,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1608719328966-40c7a0c105c3?w=500&h=500&fit=crop",
    description: "Long-lasting setting spray infused with coconut oil. 12-hour hold.",
  },
  {
    id: 19,
    name: "Berry Blush Trio",
    brand: "Natural Beauty GH",
    price: 89,
    rating: 4.8,
    reviews: 145,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1620916566398-394c4a6d4a47?w=500&h=500&fit=crop",
    description: "Three complementary blush shades for every occasion. Buildable color.",
  },
  {
    id: 20,
    name: "African Clay Face Powder",
    brand: "Ghana Glow",
    price: 110,
    rating: 4.7,
    reviews: 267,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1596462113561-c6d7a4a51c5f?w=500&h=500&fit=crop",
    description: "Oil-absorbing face powder with African clay. Matte finish all day.",
  },

  // SKINCARE (10 products)
  {
    id: 21,
    name: "Raw Shea Butter - 500g",
    brand: "Naturals Ghana",
    price: 95,
    rating: 5.0,
    reviews: 892,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1608248597279-f29d451e8e59?w=500&h=500&fit=crop",
    badge: "Bestseller",
    description: "Pure unrefined shea butter from Northern Ghana. Multi-purpose skin nourishment.",
  },
  {
    id: 22,
    name: "African Black Soap Bar",
    brand: "Naturals Ghana",
    price: 45,
    rating: 4.9,
    reviews: 1245,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1600857544200-bfd02a69c4ed?w=500&h=500&fit=crop",
    badge: "Bestseller",
    description: "Traditional African black soap handcrafted in Ghana. For all skin types.",
  },
  {
    id: 23,
    name: "Cocoa Butter Body Cream",
    brand: "Naturals Ghana",
    price: 120,
    rating: 4.8,
    reviews: 567,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1556228720-195a672d1a27?w=500&h=500&fit=crop",
    description: "Rich cocoa butter cream for deep moisturizing. Leaves skin glowing.",
  },
  {
    id: 24,
    name: "Baobab Oil Serum",
    brand: "Ghana Organics",
    price: 145,
    rating: 4.7,
    reviews: 234,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1620916566398-394c4a6d4a47?w=500&h=500&fit=crop",
    description: "Pure baobab oil for face and body. Rich in vitamins and antioxidants.",
  },
  {
    id: 25,
    name: "Moringa Face Mask",
    brand: "Naturals Ghana",
    price: 75,
    rating: 4.6,
    reviews: 189,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1598440947619-2c9a4d2c3b7e?w=500&h=500&fit=crop",
    description: "Detoxifying face mask with moringa extracts. Clears and brightens skin.",
  },
  {
    id: 26,
    name: "Coconut Oil Hair & Body Oil",
    brand: "Ghana Organics",
    price: 85,
    rating: 4.8,
    reviews: 456,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1526947425960-9c29a1a8e4c3?w=500&h=500&fit=crop",
    description: "Versatile coconut oil for hair and body. Pure and organic.",
  },
  {
    id: 27,
    name: "Shea Butter Lip Balm Set",
    brand: "Naturals Ghana",
    price: 55,
    rating: 4.9,
    reviews: 678,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1608248544094-0c0bb1e3c4c7?w=500&h=500&fit=crop",
    description: "Set of 4 nourishing lip balms with shea butter. Natural flavors.",
  },
  {
    id: 28,
    name: "Aloe Vera Gel - Pure",
    brand: "Ghana Organics",
    price: 65,
    rating: 4.7,
    reviews: 345,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a3d7c6?w=500&h=500&fit=crop",
    description: "Pure aloe vera gel for soothing and healing. Multipurpose skincare.",
  },
  {
    id: 29,
    name: "Turmeric Brightening Cream",
    brand: "Naturals Ghana",
    price: 110,
    rating: 4.6,
    reviews: 234,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1617897903114-428a8e9c7c7e?w=500&h=500&fit=crop",
    description: "Brightening cream with turmeric and shea butter. Evens skin tone.",
  },
  {
    id: 30,
    name: "Ghanaian Honey Face Wash",
    brand: "Ghana Organics",
    price: 78,
    rating: 4.8,
    reviews: 312,
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1556228578-8c9c2c5a0e6e?w=500&h=500&fit=crop",
    description: "Gentle face wash with raw Ghanaian honey. Cleanses without stripping.",
  },

  // HAIR CARE (10 products)
  {
    id: 31,
    name: "Shea Butter Hair Cream",
    brand: "Natural Hair GH",
    price: 95,
    rating: 4.8,
    reviews: 567,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500&h=500&fit=crop",
    badge: "Bestseller",
    description: "Moisturizing hair cream with raw shea butter. Perfect for natural hair.",
  },
  {
    id: 32,
    name: "Coconut Oil Hair Mask",
    brand: "Natural Hair GH",
    price: 85,
    rating: 4.7,
    reviews: 345,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1526947425960-9c29a1a8e4c3?w=500&h=500&fit=crop",
    description: "Deep conditioning hair mask with coconut oil. Repairs and strengthens.",
  },
  {
    id: 33,
    name: "African Black Soap Shampoo",
    brand: "Ghana Hair Care",
    price: 72,
    rating: 4.6,
    reviews: 289,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1608248544094-0c0bb1e3c4c7?w=500&h=500&fit=crop",
    description: "Gentle cleansing shampoo with African black soap. Sulfate-free formula.",
  },
  {
    id: 34,
    name: "Baobab Oil Hair Serum",
    brand: "Natural Hair GH",
    price: 125,
    rating: 4.9,
    reviews: 423,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1620916566398-394c4a6d4a47?w=500&h=500&fit=crop",
    description: "Lightweight hair serum with baobab oil. Adds shine without greasiness.",
  },
  {
    id: 35,
    name: "Moringa Hair Growth Oil",
    brand: "Ghana Hair Care",
    price: 110,
    rating: 4.8,
    reviews: 512,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a3d7c6?w=500&h=500&fit=crop",
    badge: "Popular",
    description: "Stimulating hair growth oil with moringa. Promotes healthy scalp.",
  },
  {
    id: 36,
    name: "Shea Butter Edge Control",
    brand: "Natural Hair GH",
    price: 65,
    rating: 4.5,
    reviews: 234,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500&h=500&fit=crop",
    description: "Strong hold edge control with shea butter. Lays edges perfectly.",
  },
  {
    id: 37,
    name: "Hibiscus Leave-In Conditioner",
    brand: "Ghana Hair Care",
    price: 89,
    rating: 4.7,
    reviews: 378,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1556228578-8c9c2c5a0e6e?w=500&h=500&fit=crop",
    description: "Moisturizing leave-in with hibiscus extract. Detangles and softens.",
  },
  {
    id: 38,
    name: "Castor Oil Growth Serum",
    brand: "Natural Hair GH",
    price: 98,
    rating: 4.8,
    reviews: 456,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1608248597279-f29d451e8e59?w=500&h=500&fit=crop",
    description: "Jamaican black castor oil blend for hair growth. Thickens and strengthens.",
  },
  {
    id: 39,
    name: "Braiding Hair Extensions",
    brand: "Ghana Hair Care",
    price: 180,
    rating: 4.6,
    reviews: 234,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=500&h=500&fit=crop",
    description: "Premium braiding hair extensions. Natural looking and durable.",
  },
  {
    id: 40,
    name: "Satin Bonnet - African Print",
    brand: "Natural Hair GH",
    price: 55,
    rating: 4.9,
    reviews: 678,
    category: "Hair Care",
    image: "https://images.unsplash.com/photo-1590779070934-0d5e57a7fd48?w=500&h=500&fit=crop",
    description: "Beautiful satin bonnet in African print. Protects hair while sleeping.",
  },

  // ACCESSORIES (10 products)
  {
    id: 41,
    name: "Gold Beaded Necklace Set",
    brand: "Adwoa's Accessories",
    price: 220,
    rating: 4.8,
    reviews: 189,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1515562140379-188d020eb96b?w=500&h=500&fit=crop",
    badge: "New",
    description: "Handmade gold beaded necklace and earring set. Traditional Ghanaian design.",
  },
  {
    id: 42,
    name: "Ankara Print Headwrap",
    brand: "Heritage Ghana",
    price: 65,
    rating: 4.9,
    reviews: 456,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1590779070934-0d5e57a7fd48?w=500&h=500&fit=crop",
    description: "Beautiful Ankara headwrap in vibrant colors. Multiple styling options.",
  },
  {
    id: 43,
    name: "Wooden Bead Bracelet Set",
    brand: "Adwoa's Accessories",
    price: 85,
    rating: 4.7,
    reviews: 234,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500&h=500&fit=crop",
    description: "Set of 5 wooden bead bracelets. Handcrafted by Ghanaian artisans.",
  },
  {
    id: 44,
    name: "Kente Clutch Bag",
    brand: "Heritage Ghana",
    price: 180,
    rating: 4.8,
    reviews: 167,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&h=500&fit=crop",
    description: "Authentic Kente clutch bag for special occasions. Fully lined interior.",
  },
  {
    id: 45,
    name: "Cowrie Shell Earrings",
    brand: "Adwoa's Accessories",
    price: 55,
    rating: 4.6,
    reviews: 312,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1535632066927-ab7a971fd5f2?w=500&h=500&fit=crop",
    description: "Beautiful cowrie shell earrings. Lightweight and elegant.",
  },
  {
    id: 46,
    name: "Beaded Waist Beads Set",
    brand: "Heritage Ghana",
    price: 75,
    rating: 4.9,
    reviews: 567,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=500&h=500&fit=crop",
    badge: "Popular",
    description: "Traditional waist beads in beautiful colors. Adjustable fit.",
  },
  {
    id: 47,
    name: "Ankara Print Tote Bag",
    brand: "Adwoa's Accessories",
    price: 145,
    rating: 4.7,
    reviews: 234,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop",
    description: "Spacious tote bag in Ankara print. Perfect for everyday use.",
  },
  {
    id: 48,
    name: "Brass Cuff Bangle",
    brand: "Heritage Ghana",
    price: 120,
    rating: 4.8,
    reviews: 189,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500&h=500&fit=crop",
    description: "Handcrafted brass cuff bangle. Traditional Ghanaian design.",
  },
  {
    id: 49,
    name: "African Print Scarf",
    brand: "Adwoa's Accessories",
    price: 95,
    rating: 4.6,
    reviews: 178,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1601924994989-1a0aeb67d9b0?w=500&h=500&fit=crop",
    description: "Versatile African print scarf. Can be worn multiple ways.",
  },
  {
    id: 50,
    name: "Statement Gold Earrings",
    brand: "Heritage Ghana",
    price: 135,
    rating: 4.9,
    reviews: 345,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1535632066927-ab7a971fd5f2?w=500&h=500&fit=crop",
    description: "Bold statement earrings in gold. Perfect for special occasions.",
  },
];

export const categories = [
  {
    id: 1,
    name: "Fashion",
    description: "Ankara, Kente & African Wear",
    image: "https://res.cloudinary.com/dwsl2ktt2/image/upload/v1778669947/adaw_tld2fa.avif",
    count: 10,
  },
  {
    id: 2,
    name: "Cosmetics",
    description: "Makeup & Beauty Products",
    image: "https://res.cloudinary.com/dwsl2ktt2/image/upload/v1778669947/uyy_ixp2x1.avif",
    count: 10,
  },
  {
    id: 3,
    name: "Skincare",
    description: "Natural & Organic Care",
    image: "https://res.cloudinary.com/dwsl2ktt2/image/upload/v1778669947/lk_oyxxa6.avif",
    count: 10,
  },
  {
    id: 4,
    name: "Hair Care",
    description: "Natural Hair Products",
    image: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=400&h=400&fit=crop",
    count: 10,
  },
  {
    id: 5,
    name: "Accessories",
    description: "Jewelry & Fashion Items",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop",
    count: 10,
  },
];