export interface Product {
  id: number;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  category: string;
  image: string;
  badge?: string;
  stock: number;
  description: string;
}

export const products: Product[] = [
  // FASHION - ANKARA & AFRICAN WEAR (10 products)
  {
    id: 1,
    name: "Ankara Maxi Dress",
    brand: "Adwoa's Collection",
    price: 350,
    originalPrice: 450,
    rating: 4.8,
    reviews: 124,
    category: "Fashion",
    image: "yyyr_rrilrc",
    badge: "Sale",
    stock: 15,
    description: "Beautiful Ankara maxi dress with modern cut. Perfect for weddings and special occasions.",
  },
  {
    id: 2,
    name: "Kente Wrap Skirt",
    brand: "Heritage Ghana",
    price: 280,
    rating: 4.9,
    reviews: 89,
    category: "Fashion",
    image: "xxx_peeq9k",
    badge: "New",
    stock: 8,
    description: "Authentic Kente wrap skirt handwoven by Ghanaian artisans. A timeless piece.",
  },
  {
    id: 3,
    name: "Ankara Peplum Blouse",
    brand: "Adwoa's Collection",
    price: 180,
    rating: 4.7,
    reviews: 156,
    category: "Fashion",
    image: "jjb_pwzexw",
    stock: 20,
    description: "Stylish peplum blouse in vibrant Ankara print. Pairs perfectly with skirts or trousers.",
  },
  {
    id: 4,
    name: "African Print Jumpsuit",
    brand: "Modern Afrika",
    price: 420,
    originalPrice: 520,
    rating: 4.6,
    reviews: 78,
    category: "Fashion",
    image: "yyyy_woib3l",
    badge: "Sale",
    stock: 5,
    description: "Contemporary jumpsuit with traditional African print. Modern elegance meets heritage.",
  },
  {
    id: 5,
    name: "Kente Evening Gown",
    brand: "Heritage Ghana",
    price: 850,
    rating: 5.0,
    reviews: 45,
    category: "Fashion",
    image: "adaw_tld2fa",
    badge: "Premium",
    stock: 3,
    description: "Luxurious Kente evening gown for the most special occasions. Handwoven excellence.",
  },
  {
    id: 6,
    name: "Ankara Shift Dress",
    brand: "Adwoa's Collection",
    price: 290,
    rating: 4.5,
    reviews: 203,
    category: "Fashion",
    image: "yyyr_rrilrc",
    stock: 12,
    description: "Comfortable shift dress in beautiful Ankara fabric. Perfect for work or casual outings.",
  },
  {
    id: 7,
    name: "Dashiki Maxi Kaftan",
    brand: "Modern Afrika",
    price: 320,
    rating: 4.8,
    reviews: 167,
    category: "Fashion",
    image: "xxx_peeq9k",
    stock: 18,
    description: "Elegant dashiki kaftan in rich colors. Comfortable and stylish for any occasion.",
  },
  {
    id: 8,
    name: "Ankara Palazzo Pants",
    brand: "Adwoa's Collection",
    price: 220,
    rating: 4.6,
    reviews: 134,
    category: "Fashion",
    image: "jjb_pwzexw",
    stock: 25,
    description: "Flowy palazzo pants in stunning Ankara print. Comfort meets style.",
  },
  {
    id: 9,
    name: "Boubou African Dress",
    brand: "Heritage Ghana",
    price: 380,
    rating: 4.7,
    reviews: 92,
    category: "Fashion",
    image: "yyyy_woib3l",
    stock: 7,
    description: "Traditional Boubou dress with modern touches. Perfect for cultural events.",
  },
  {
    id: 10,
    name: "Ankara Kimono Jacket",
    brand: "Modern Afrika",
    price: 195,
    originalPrice: 250,
    rating: 4.9,
    reviews: 211,
    category: "Fashion",
    image: "adaw_tld2fa",
    badge: "Sale",
    stock: 14,
    description: "Versatile kimono jacket that transforms any outfit. A statement piece.",
  },

  // COSMETICS & MAKEUP (10 products)
  {
    id: 11,
    name: "Shea Butter Lip Gloss Set",
    brand: "Ghana Glow",
    price: 85,
    rating: 4.8,
    reviews: 342,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    badge: "Bestseller",
    stock: 30,
    description: "Nourishing lip gloss set infused with Ghanaian shea butter. 6 gorgeous shades.",
  },
  {
    id: 12,
    name: "Natural Foundation - Cocoa",
    brand: "Ghana Glow",
    price: 120,
    rating: 4.7,
    reviews: 289,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    stock: 22,
    description: "Full coverage foundation made for African skin tones. 12 shades available.",
  },
  {
    id: 13,
    name: "African Black Soap Mascara",
    brand: "Natural Beauty GH",
    price: 65,
    rating: 4.6,
    reviews: 178,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    stock: 45,
    description: "Lengthening mascara with African black soap extracts. Gentle and effective.",
  },
  {
    id: 14,
    name: "Kente Inspired Eyeshadow Palette",
    brand: "Ghana Glow",
    price: 150,
    rating: 4.9,
    reviews: 456,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    badge: "New",
    stock: 19,
    description: "Vibrant eyeshadow palette inspired by Kente colors. 18 stunning shades.",
  },
  {
    id: 15,
    name: "Shea Butter Highlighter",
    brand: "Natural Beauty GH",
    price: 95,
    rating: 4.8,
    reviews: 234,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    stock: 28,
    description: "Glowing highlighter with shea butter for smooth application. Golden shimmer.",
  },
  {
    id: 16,
    name: "Cocoa Butter Contour Kit",
    brand: "Ghana Glow",
    price: 135,
    rating: 4.7,
    reviews: 167,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    stock: 16,
    description: "Complete contour and bronzing kit. Perfect for sculpting African features.",
  },
  {
    id: 17,
    name: "Natural Brow Gel Duo",
    brand: "Natural Beauty GH",
    price: 55,
    rating: 4.5,
    reviews: 198,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    stock: 50,
    description: "Dual-ended brow gel for perfectly defined brows. Long-lasting formula.",
  },
  {
    id: 18,
    name: "Coconut Oil Setting Spray",
    brand: "Ghana Glow",
    price: 75,
    rating: 4.6,
    reviews: 312,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    stock: 33,
    description: "Long-lasting setting spray infused with coconut oil. 12-hour hold.",
  },
  {
    id: 19,
    name: "Berry Blush Trio",
    brand: "Natural Beauty GH",
    price: 89,
    rating: 4.8,
    reviews: 145,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    stock: 24,
    description: "Three complementary blush shades for every occasion. Buildable color.",
  },
  {
    id: 20,
    name: "African Clay Face Powder",
    brand: "Ghana Glow",
    price: 110,
    rating: 4.7,
    reviews: 267,
    category: "Cosmetics",
    image: "uyy_ixp2x1",
    stock: 20,
    description: "Oil-absorbing face powder with African clay. Matte finish all day.",
  },

  // SKINCARE (10 products)
  {
    id: 21,
    name: "Raw Shea Butter - 500g",
    brand: "Naturals Ghana",
    price: 95,
    rating: 5.0,
    reviews: 892,
    category: "Skincare",
    image: "lk_oyxxa6",
    badge: "Bestseller",
    stock: 50,
    description: "Pure unrefined shea butter from Northern Ghana. Multi-purpose skin nourishment.",
  },
  {
    id: 22,
    name: "African Black Soap Bar",
    brand: "Naturals Ghana",
    price: 45,
    rating: 4.9,
    reviews: 1245,
    category: "Skincare",
    image: "lk_oyxxa6",
    badge: "Bestseller",
    stock: 80,
    description: "Traditional African black soap handcrafted in Ghana. For all skin types.",
  },
  {
    id: 23,
    name: "Cocoa Butter Body Cream",
    brand: "Naturals Ghana",
    price: 120,
    rating: 4.8,
    reviews: 567,
    category: "Skincare",
    image: "lk_oyxxa6",
    stock: 35,
    description: "Rich cocoa butter cream for deep moisturizing. Leaves skin glowing.",
  },
  {
    id: 24,
    name: "Baobab Oil Serum",
    brand: "Ghana Organics",
    price: 145,
    rating: 4.7,
    reviews: 234,
    category: "Skincare",
    image: "lk_oyxxa6",
    stock: 28,
    description: "Pure baobab oil for face and body. Rich in vitamins and antioxidants.",
  },
  {
    id: 25,
    name: "Moringa Face Mask",
    brand: "Naturals Ghana",
    price: 75,
    rating: 4.6,
    reviews: 189,
    category: "Skincare",
    image: "lk_oyxxa6",
    stock: 42,
    description: "Detoxifying face mask with moringa extracts. Clears and brightens skin.",
  },
  {
    id: 26,
    name: "Coconut Oil Hair & Body Oil",
    brand: "Ghana Organics",
    price: 85,
    rating: 4.8,
    reviews: 456,
    category: "Skincare",
    image: "lk_oyxxa6",
    stock: 60,
    description: "Versatile coconut oil for hair and body. Pure and organic.",
  },
  {
    id: 27,
    name: "Shea Butter Lip Balm Set",
    brand: "Naturals Ghana",
    price: 55,
    rating: 4.9,
    reviews: 678,
    category: "Skincare",
    image: "lk_oyxxa6",
    stock: 55,
    description: "Set of 4 nourishing lip balms with shea butter. Natural flavors.",
  },
  {
    id: 28,
    name: "Aloe Vera Gel - Pure",
    brand: "Ghana Organics",
    price: 65,
    rating: 4.7,
    reviews: 345,
    category: "Skincare",
    image: "lk_oyxxa6",
    stock: 48,
    description: "Pure aloe vera gel for soothing and healing. Multipurpose skincare.",
  },
  {
    id: 29,
    name: "Turmeric Brightening Cream",
    brand: "Naturals Ghana",
    price: 110,
    rating: 4.6,
    reviews: 234,
    category: "Skincare",
    image: "lk_oyxxa6",
    stock: 30,
    description: "Brightening cream with turmeric and shea butter. Evens skin tone.",
  },
  {
    id: 30,
    name: "Ghanaian Honey Face Wash",
    brand: "Ghana Organics",
    price: 78,
    rating: 4.8,
    reviews: 312,
    category: "Skincare",
    image: "lk_oyxxa6",
    stock: 38,
    description: "Gentle face wash with raw Ghanaian honey. Cleanses without stripping.",
  },

  // HAIR CARE (10 products)
  {
    id: 31,
    name: "Shea Butter Hair Cream",
    brand: "Natural Hair GH",
    price: 95,
    rating: 4.8,
    reviews: 567,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    badge: "Bestseller",
    stock: 40,
    description: "Moisturizing hair cream with raw shea butter. Perfect for natural hair.",
  },
  {
    id: 32,
    name: "Coconut Oil Hair Mask",
    brand: "Natural Hair GH",
    price: 85,
    rating: 4.7,
    reviews: 345,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    stock: 25,
    description: "Deep conditioning hair mask with coconut oil. Repairs and strengthens.",
  },
  {
    id: 33,
    name: "African Black Soap Shampoo",
    brand: "Ghana Hair Care",
    price: 72,
    rating: 4.6,
    reviews: 289,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    stock: 33,
    description: "Gentle cleansing shampoo with African black soap. Sulfate-free formula.",
  },
  {
    id: 34,
    name: "Baobab Oil Hair Serum",
    brand: "Natural Hair GH",
    price: 125,
    rating: 4.9,
    reviews: 423,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    stock: 20,
    description: "Lightweight hair serum with baobab oil. Adds shine without greasiness.",
  },
  {
    id: 35,
    name: "Moringa Hair Growth Oil",
    brand: "Ghana Hair Care",
    price: 110,
    rating: 4.8,
    reviews: 512,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    badge: "Popular",
    stock: 18,
    description: "Stimulating hair growth oil with moringa. Promotes healthy scalp.",
  },
  {
    id: 36,
    name: "Shea Butter Edge Control",
    brand: "Natural Hair GH",
    price: 65,
    rating: 4.5,
    reviews: 234,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    stock: 45,
    description: "Strong hold edge control with shea butter. Lays edges perfectly.",
  },
  {
    id: 37,
    name: "Hibiscus Leave-In Conditioner",
    brand: "Ghana Hair Care",
    price: 89,
    rating: 4.7,
    reviews: 378,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    stock: 30,
    description: "Moisturizing leave-in with hibiscus extract. Detangles and softens.",
  },
  {
    id: 38,
    name: "Castor Oil Growth Serum",
    brand: "Natural Hair GH",
    price: 98,
    rating: 4.8,
    reviews: 456,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    stock: 22,
    description: "Jamaican black castor oil blend for hair growth. Thickens and strengthens.",
  },
  {
    id: 39,
    name: "Braiding Hair Extensions",
    brand: "Ghana Hair Care",
    price: 180,
    rating: 4.6,
    reviews: 234,
    category: "Hair Care",
    image: "uyy_ixp2x1",
    stock: 15,
    description: "Premium braiding hair extensions. Natural looking and durable.",
  },
  {
    id: 40,
    name: "Satin Bonnet - African Print",
    brand: "Natural Hair GH",
    price: 55,
    rating: 4.9,
    reviews: 678,
    category: "Hair Care",
    image: "adaw_tld2fa",
    stock: 50,
    description: "Beautiful satin bonnet in African print. Protects hair while sleeping.",
  },

  // ACCESSORIES (10 products)
  {
    id: 41,
    name: "Gold Beaded Necklace Set",
    brand: "Adwoa's Accessories",
    price: 220,
    rating: 4.8,
    reviews: 189,
    category: "Accessories",
    image: "adaw_tld2fa",
    badge: "New",
    stock: 22,
    description: "Handmade gold beaded necklace and earring set. Traditional Ghanaian design.",
  },
  {
    id: 42,
    name: "Ankara Print Headwrap",
    brand: "Heritage Ghana",
    price: 65,
    rating: 4.9,
    reviews: 456,
    category: "Accessories",
    image: "adaw_tld2fa",
    stock: 40,
    description: "Beautiful Ankara headwrap in vibrant colors. Multiple styling options.",
  },
  {
    id: 43,
    name: "Wooden Bead Bracelet Set",
    brand: "Adwoa's Accessories",
    price: 85,
    rating: 4.7,
    reviews: 234,
    category: "Accessories",
    image: "adaw_tld2fa",
    stock: 35,
    description: "Set of 5 wooden bead bracelets. Handcrafted by Ghanaian artisans.",
  },
  {
    id: 44,
    name: "Kente Clutch Bag",
    brand: "Heritage Ghana",
    price: 180,
    rating: 4.8,
    reviews: 167,
    category: "Accessories",
    image: "jjb_pwzexw",
    stock: 12,
    description: "Authentic Kente clutch bag for special occasions. Fully lined interior.",
  },
  {
    id: 45,
    name: "Cowrie Shell Earrings",
    brand: "Adwoa's Accessories",
    price: 55,
    rating: 4.6,
    reviews: 312,
    category: "Accessories",
    image: "adaw_tld2fa",
    stock: 48,
    description: "Beautiful cowrie shell earrings. Lightweight and elegant.",
  },
  {
    id: 46,
    name: "Beaded Waist Beads Set",
    brand: "Heritage Ghana",
    price: 75,
    rating: 4.9,
    reviews: 567,
    category: "Accessories",
    image: "adaw_tld2fa",
    badge: "Popular",
    stock: 55,
    description: "Traditional waist beads in beautiful colors. Adjustable fit.",
  },
  {
    id: 47,
    name: "Ankara Print Tote Bag",
    brand: "Adwoa's Accessories",
    price: 145,
    rating: 4.7,
    reviews: 234,
    category: "Accessories",
    image: "jjb_pwzexw",
    stock: 18,
    description: "Spacious tote bag in Ankara print. Perfect for everyday use.",
  },
  {
    id: 48,
    name: "Brass Cuff Bangle",
    brand: "Heritage Ghana",
    price: 120,
    rating: 4.8,
    reviews: 189,
    category: "Accessories",
    image: "adaw_tld2fa",
    stock: 27,
    description: "Handcrafted brass cuff bangle. Traditional Ghanaian design.",
  },
  {
    id: 49,
    name: "African Print Scarf",
    brand: "Adwoa's Accessories",
    price: 95,
    rating: 4.6,
    reviews: 178,
    category: "Accessories",
    image: "adaw_tld2fa",
    stock: 32,
    description: "Versatile African print scarf. Can be worn multiple ways.",
  },
  {
    id: 50,
    name: "Statement Gold Earrings",
    brand: "Heritage Ghana",
    price: 135,
    rating: 4.9,
    reviews: 345,
    category: "Accessories",
    image: "adaw_tld2fa",
    stock: 20,
    description: "Bold statement earrings in gold. Perfect for special occasions.",
  },
];

export const categories = [
  {
    id: 1,
    name: "Fashion",
    description: "Ankara, Kente & African Wear",
    image: "adaw_tld2fa",
    count: 10,
  },
  {
    id: 2,
    name: "Cosmetics",
    description: "Makeup & Beauty Products",
    image: "uyy_ixp2x1",
    count: 10,
  },
  {
    id: 3,
    name: "Skincare",
    description: "Natural & Organic Care",
    image: "lk_oyxxa6",
    count: 10,
  },
  {
    id: 4,
    name: "Hair Care",
    description: "Natural Hair Products",
    image: "uyy_ixp2x1",
    count: 10,
  },
  {
    id: 5,
    name: "Accessories",
    description: "Jewelry & Fashion Items",
    image: "adaw_tld2fa",
    count: 10,
  },
];